version: "3.7"

services:

  mysql_db:
    container_name: myapp_mysql
    image: mysql:5.7
    restart: always
    expose:
      - 3307
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql_db
    depends_on:
      - mysql_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080
    environment:
      ADMINER_HOST: mysql_db
      ADMINER_DATABASE: ${DATABASE_NAME}
    depends_on:
      - mysql_db

volumes:
  mysql_data:
    name: mysql_data