version: "3.7"

services:
  db:
    container_name: myapp_mysql
    image: mysql:5.7
    restart: always
    expose:
      - 3307
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
    - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    name: mysql_data
